/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometricsauthentication;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
        

/**
 *
 * @author manjitha
 */

public class AddUser extends javax.swing.JFrame implements KeyListener{

    /**
     * Creates new form AddUser
     */
    private GUI parent;
    private getPattern get;
    private int semerphore,semerphore2;
    private double timeT,totalTIme;
    private double t,t2;
    public AddUser(GUI parent,getPattern get) {
        initComponents();
        this.parent = parent;
        this.get = get;
        System.out.println(get.getName());
        semerphore = 0;
        KeyListener listener = new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                //System.out.println(e.getKeyCode());  
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if(semerphore == 0){
                    t = System.currentTimeMillis();
                    semerphore = 1;
                    //System.out.println(e.getKeyCode() + "****"); 
                    //System.out.println(parent.time);
                    
                }
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (semerphore == 1){
                    semerphore = 0;
                    t2 = System.currentTimeMillis();
                    timeT = t2-t;
                    parent.time.add(timeT);
                    //System.out.println(parent.time);
                }
               
            }
        };
        KeyListener listener2 = new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                //System.out.println(e.getKeyCode());  
            }

            @Override
            public synchronized void keyPressed(KeyEvent e) {
                if(semerphore2 == 0){
                    t = System.currentTimeMillis();
                    semerphore2 = 1;
                    //System.out.println(e.getKeyCode() + "****"); 
                    //System.out.println(parent.time2);
                    
                }
                
            }

            @Override
            public synchronized void keyReleased(KeyEvent e) {
                if (semerphore2 == 1){
                    semerphore2 = 0;
                    t2 = System.currentTimeMillis();
                    timeT = t2-t;
                    parent.time2.add(timeT);
                }
               
            }
        };
        this.input1.addKeyListener(listener);
        this.input2.addKeyListener(listener2);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBackinAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        input2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmitAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Add New User");

        btnBackinAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackinAdd.setText("Back");
        btnBackinAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackinAddActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("i am a student");

        jLabel3.setText("Type above sentence here");

        input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Re-Type above sentece here");

        btnSubmitAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmitAdd.setText("Submit");
        btnSubmitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBackinAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSubmitAdd)
                        .addGap(243, 243, 243))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnSubmitAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnBackinAdd)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackinAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackinAddActionPerformed
        // TODO add your handling code here:
        hideme();
        get.setVisible(true);
    }//GEN-LAST:event_btnBackinAddActionPerformed

    private void input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input2ActionPerformed

    private void btnSubmitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAddActionPerformed
        // TODO add your handling code here:
        //System.out.println(parent.time.size()+" "+ parent.time2.size());
        if (parent.time.size() != parent.time2.size()){
            JOptionPane.showMessageDialog(null, "         Add user failed!\nCan't recognize keystoke pattern \n                Try again");
            GUI gui = new GUI();
            gui.setVisible(true);
        }else{
            
            for(int i = 0; i < parent.time.size();i++){
                parent.finalTime.add(parent.time.get(i)/2 + parent.time.get(i)/2);
            }
            GUI.hm.put(get.getIndex(),parent.finalTime);
            JOptionPane.showMessageDialog(null, "User registered successfully!");
            hideme();
            //System.out.println(parent.finalTime.size());
            parent.setVisible(true);
            }
    }//GEN-LAST:event_btnSubmitAddActionPerformed
    
    
    
    private void visibleme(){
        this.setVisible(true);
    }
    
    private void hideme(){
        this.setVisible(false);
    }
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackinAdd;
    private javax.swing.JButton btnSubmitAdd;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 
    
}
