/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometricsauthentication;

import java.util.ArrayList;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author manjitha
 */
public class login extends javax.swing.JFrame implements KeyListener{

    /**
     * Creates new form login
     */
    private GUI parent;
    private int semerphore,correct;
    private double t,t2,timeT,totalTime;
    private ArrayList<Double> loginArray = new ArrayList<Double>();
    public login(GUI parent) {
        initComponents();
        this.parent = parent;
        semerphore = 0;
        KeyListener listener = new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                //System.out.println(e.getKeyCode());  
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if(semerphore == 0){
                    t = System.currentTimeMillis();
                    semerphore = 1;
                    //System.out.println(e.getKeyCode() + "****"); 
                    //System.out.println(loginArray);
                    
                }
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (semerphore == 1){
                    semerphore = 0;
                    t2 = System.currentTimeMillis();
                    timeT = t2-t;
                    loginArray.add(timeT);
                }
               
            }
        };
        this.input.addKeyListener(listener);
    }
    
    public login(GUI parent,String index) {
        initComponents();
        this.parent = parent;
        indexLogin.setText(index);
        input.requestFocus();
        semerphore = 0;
        KeyListener listener = new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                //System.out.println(e.getKeyCode());  
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if(semerphore == 0){
                    t = System.currentTimeMillis();
                    semerphore = 1;
                    //System.out.println(e.getKeyCode() + "****"); 
                    //System.out.println(loginArray);
                    
                }
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (semerphore == 1){
                    semerphore = 0;
                    t2 = System.currentTimeMillis();
                    timeT = t2-t;
                    loginArray.add(timeT);
                }
               
            }
        };
        this.input.addKeyListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBackinLogin = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enterLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        indexLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Login");

        btnBackinLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackinLogin.setText("Back");
        btnBackinLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackinLoginActionPerformed(evt);
            }
        });

        input.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setText("                  Type above sentence here");

        enterLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterLogin.setText("Enter");
        enterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterLoginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("      i am a student");

        jLabel3.setText("Enter your Index number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(btnBackinLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(enterLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(indexLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(enterLogin)
                .addGap(33, 33, 33)
                .addComponent(btnBackinLogin)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackinLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackinLoginActionPerformed
        // TODO add your handling code here:
        hideme();
        parent.setVisible(true);
    }//GEN-LAST:event_btnBackinLoginActionPerformed

    private void enterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterLoginActionPerformed
            // TODO add your handling code here:
            correct = 0;
            ArrayList<Double> finalTime = parent.hm.get(this.indexLogin.getText());
            if( !parent.hm.containsKey(this.indexLogin.getText())){
                JOptionPane.showMessageDialog(null, "       Error Login!\nPlease sign in first");
                hideme();
                parent.setVisible(true);
            }else if (loginArray.size() != finalTime.size()){
                JOptionPane.showMessageDialog(null, "Login Failed!\n  Try Again");
                login lg = new login(parent,indexLogin.getText());
                hideme();
                lg.setVisible(true);
            }else{
                for(int i = 0;i < loginArray.size();i++){
                    if ((loginArray.get(i)- finalTime.get(i)) <= 100 ){
                        correct ++;
                    }
                }
                if (correct/loginArray.size()*100 > 75){
                    JOptionPane.showMessageDialog(null, "      Successfull!\nWelcome "+indexLogin.getText());
                    GUI gui = new GUI();
                    hideme();
                    gui.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Login Failed!");
                    login lg = new login(parent,indexLogin.getText());
                    hideme();
                    lg.setVisible(true);
                }
            }
            
    }//GEN-LAST:event_enterLoginActionPerformed
    
    private void visibleme(){
        this.setVisible(true);
    }
    
    private void hideme(){
        this.setVisible(false);
    }
            
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackinLogin;
    private javax.swing.JButton enterLogin;
    private javax.swing.JTextField indexLogin;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
